/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author messi
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtaProce = new javax.swing.JTextArea();
        txtfResul = new javax.swing.JTextField();
        btnCalcu = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtfCantNum = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtaCompro = new javax.swing.JTextArea();
        txtfBase = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtaProce.setColumns(20);
        txtaProce.setRows(5);
        jScrollPane1.setViewportView(txtaProce);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 330, 240));

        txtfResul.setEditable(false);
        getContentPane().add(txtfResul, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 480, 30));

        btnCalcu.setText("CALCULAR");
        getContentPane().add(btnCalcu, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("DIGITE LA OPERACIÓN");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, -1, 30));
        getContentPane().add(txtfCantNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 320, 50));

        txtaCompro.setColumns(20);
        txtaCompro.setRows(5);
        jScrollPane2.setViewportView(txtaCompro);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 380, 330, 240));
        getContentPane().add(txtfBase, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, 50, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("BASE");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(507, 140, 40, 20));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("PROCEDIMIENTO");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("COMPROBACIÓN");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 350, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fsum2.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtaCompro;
    private javax.swing.JTextArea txtaProce;
    private javax.swing.JTextField txtfBase;
    private javax.swing.JTextField txtfCantNum;
    private javax.swing.JTextField txtfResul;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnCalcu() {
        return btnCalcu;
    }

    public void setBtnCalcu(JButton btnCalcu) {
        this.btnCalcu = btnCalcu;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public JLabel getjLabel5() {
        return jLabel5;
    }

    public void setjLabel5(JLabel jLabel5) {
        this.jLabel5 = jLabel5;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }

    public void setjScrollPane2(JScrollPane jScrollPane2) {
        this.jScrollPane2 = jScrollPane2;
    }

    public JTextArea getTxtaCompro() {
        return txtaCompro;
    }

    public void setTxtaCompro(JTextArea txtaCompro) {
        this.txtaCompro = txtaCompro;
    }

    public JTextArea getTxtaProce() {
        return txtaProce;
    }

    public void setTxtaProce(JTextArea txtaProce) {
        this.txtaProce = txtaProce;
    }

    public JTextField getTxtfBase() {
        return txtfBase;
    }

    public void setTxtfBase(JTextField txtfBase) {
        this.txtfBase = txtfBase;
    }

    public JTextField getTxtfCantNum() {
        return txtfCantNum;
    }

    public void setTxtfCantNum(JTextField txtfCantNum) {
        this.txtfCantNum = txtfCantNum;
    }

    public JTextField getTxtfResul() {
        return txtfResul;
    }

    public void setTxtfResul(JTextField txtfResul) {
        this.txtfResul = txtfResul;
    }


    


    
}
